//! Curated emoji catalog for the in-app picker.
//!
//! The macOS emoji picker (⌃⌘Space) silently drops characters in iced
//! 0.14 because winit's macOS `insertText:` only emits `Ime::Commit`
//! when there's marked text, and the system picker injects without
//! composition (see winit/src/platform_impl/macos/view.rs:411).
//! This module powers a built-in picker that bypasses the bug.
//!
//! Selection is curated, not exhaustive: ~280 of the most common
//! emojis. Regenerate ~yearly from emojibase to pick up new Unicode
//! ranges. No flags or skin-tone modifiers (multi-codepoint sequences
//! complicate keyboard nav and grid layout).

#[derive(Clone, Copy, PartialEq, Eq, Hash)]
pub enum Category {
    Smileys,
    People,
    Animals,
    Food,
    Activities,
    Travel,
    Objects,
    Symbols,
}

impl Category {
    pub const ALL: &'static [Category] = &[
        Category::Smileys,
        Category::People,
        Category::Animals,
        Category::Food,
        Category::Activities,
        Category::Travel,
        Category::Objects,
        Category::Symbols,
    ];

    #[allow(dead_code)]
    pub fn label(self) -> &'static str {
        match self {
            Category::Smileys => "smileys",
            Category::People => "people",
            Category::Animals => "animals",
            Category::Food => "food",
            Category::Activities => "activity",
            Category::Travel => "travel",
            Category::Objects => "objects",
            Category::Symbols => "symbols",
        }
    }

    pub fn glyph(self) -> &'static str {
        match self {
            Category::Smileys => "😀",
            Category::People => "👋",
            Category::Animals => "🐶",
            Category::Food => "🍎",
            Category::Activities => "⚽",
            Category::Travel => "🚗",
            Category::Objects => "💡",
            Category::Symbols => "❤️",
        }
    }
}

pub struct Entry {
    pub ch: &'static str,
    pub name: &'static str,
    pub shortcode: &'static str,
    pub keywords: &'static [&'static str],
    pub category: Category,
}

/// Returns the entry matching `shortcode` (case-insensitive, with or
/// without surrounding colons), or `None`. Kept for future `:slug:`
/// expansion in the compose buffer.
#[allow(dead_code)]
pub fn by_shortcode(s: &str) -> Option<&'static Entry> {
    let s = s.trim().trim_matches(':').to_ascii_lowercase();
    CATALOG.iter().find(|e| e.shortcode.eq_ignore_ascii_case(&s))
}

/// Filters the catalog by category and query. An empty query returns
/// every emoji in the category. Query matches against shortcode, name,
/// and keywords (substring, case-insensitive).
pub fn filter<'a>(
    category: Option<Category>,
    query: &'a str,
) -> impl Iterator<Item = &'static Entry> + 'a {
    let q = query.trim().to_ascii_lowercase();
    CATALOG.iter().filter(move |e| {
        if let Some(c) = category {
            if e.category != c {
                return false;
            }
        }
        if q.is_empty() {
            return true;
        }
        if e.shortcode.contains(&q) || e.name.to_ascii_lowercase().contains(&q) {
            return true;
        }
        e.keywords
            .iter()
            .any(|k| k.to_ascii_lowercase().contains(&q))
    })
}

const CATALOG: &[Entry] = &[
    // ── smileys ──
    Entry { ch: "😀", name: "grinning face", shortcode: "grinning", keywords: &["smile", "happy"], category: Category::Smileys },
    Entry { ch: "😃", name: "grinning face with big eyes", shortcode: "smiley", keywords: &["happy", "joy"], category: Category::Smileys },
    Entry { ch: "😄", name: "grinning face with smiling eyes", shortcode: "smile", keywords: &["happy", "joy", "laugh"], category: Category::Smileys },
    Entry { ch: "😁", name: "beaming face with smiling eyes", shortcode: "grin", keywords: &["happy"], category: Category::Smileys },
    Entry { ch: "😆", name: "grinning squinting face", shortcode: "laughing", keywords: &["happy", "haha", "lol"], category: Category::Smileys },
    Entry { ch: "😅", name: "grinning face with sweat", shortcode: "sweat_smile", keywords: &["hot", "relief"], category: Category::Smileys },
    Entry { ch: "🤣", name: "rolling on the floor laughing", shortcode: "rofl", keywords: &["lol", "haha"], category: Category::Smileys },
    Entry { ch: "😂", name: "face with tears of joy", shortcode: "joy", keywords: &["laugh", "cry", "lol"], category: Category::Smileys },
    Entry { ch: "🙂", name: "slightly smiling face", shortcode: "slightly_smiling_face", keywords: &["smile"], category: Category::Smileys },
    Entry { ch: "🙃", name: "upside-down face", shortcode: "upside_down_face", keywords: &["sarcasm", "silly"], category: Category::Smileys },
    Entry { ch: "😉", name: "winking face", shortcode: "wink", keywords: &["flirt"], category: Category::Smileys },
    Entry { ch: "😊", name: "smiling face with smiling eyes", shortcode: "blush", keywords: &["happy", "smile"], category: Category::Smileys },
    Entry { ch: "😇", name: "smiling face with halo", shortcode: "innocent", keywords: &["angel"], category: Category::Smileys },
    Entry { ch: "🥰", name: "smiling face with hearts", shortcode: "smiling_face_with_three_hearts", keywords: &["love", "adore"], category: Category::Smileys },
    Entry { ch: "😍", name: "smiling face with heart-eyes", shortcode: "heart_eyes", keywords: &["love"], category: Category::Smileys },
    Entry { ch: "🤩", name: "star-struck", shortcode: "star_struck", keywords: &["excited"], category: Category::Smileys },
    Entry { ch: "😘", name: "face blowing a kiss", shortcode: "kissing_heart", keywords: &["kiss"], category: Category::Smileys },
    Entry { ch: "😗", name: "kissing face", shortcode: "kissing", keywords: &["kiss"], category: Category::Smileys },
    Entry { ch: "😚", name: "kissing face with closed eyes", shortcode: "kissing_closed_eyes", keywords: &["kiss"], category: Category::Smileys },
    Entry { ch: "😙", name: "kissing face with smiling eyes", shortcode: "kissing_smiling_eyes", keywords: &["kiss"], category: Category::Smileys },
    Entry { ch: "🥲", name: "smiling face with tear", shortcode: "smiling_face_with_tear", keywords: &["proud", "happy", "sad"], category: Category::Smileys },
    Entry { ch: "😋", name: "face savoring food", shortcode: "yum", keywords: &["tongue", "tasty"], category: Category::Smileys },
    Entry { ch: "😛", name: "face with tongue", shortcode: "stuck_out_tongue", keywords: &["playful"], category: Category::Smileys },
    Entry { ch: "😜", name: "winking face with tongue", shortcode: "stuck_out_tongue_winking_eye", keywords: &["playful"], category: Category::Smileys },
    Entry { ch: "🤪", name: "zany face", shortcode: "zany_face", keywords: &["crazy", "silly"], category: Category::Smileys },
    Entry { ch: "😝", name: "squinting face with tongue", shortcode: "stuck_out_tongue_closed_eyes", keywords: &["playful"], category: Category::Smileys },
    Entry { ch: "🤑", name: "money-mouth face", shortcode: "money_mouth_face", keywords: &["dollar", "rich"], category: Category::Smileys },
    Entry { ch: "🤗", name: "smiling face with open hands", shortcode: "hugs", keywords: &["hug"], category: Category::Smileys },
    Entry { ch: "🤭", name: "face with hand over mouth", shortcode: "hand_over_mouth", keywords: &["whoops", "oops"], category: Category::Smileys },
    Entry { ch: "🤫", name: "shushing face", shortcode: "shushing_face", keywords: &["quiet", "shh"], category: Category::Smileys },
    Entry { ch: "🤔", name: "thinking face", shortcode: "thinking", keywords: &["hmm", "consider"], category: Category::Smileys },
    Entry { ch: "🤐", name: "zipper-mouth face", shortcode: "zipper_mouth_face", keywords: &["silence"], category: Category::Smileys },
    Entry { ch: "🤨", name: "face with raised eyebrow", shortcode: "raised_eyebrow", keywords: &["suspicious", "skeptical"], category: Category::Smileys },
    Entry { ch: "😐", name: "neutral face", shortcode: "neutral_face", keywords: &["meh"], category: Category::Smileys },
    Entry { ch: "😑", name: "expressionless face", shortcode: "expressionless", keywords: &["blank"], category: Category::Smileys },
    Entry { ch: "😶", name: "face without mouth", shortcode: "no_mouth", keywords: &["silent"], category: Category::Smileys },
    Entry { ch: "😏", name: "smirking face", shortcode: "smirk", keywords: &["smug"], category: Category::Smileys },
    Entry { ch: "😒", name: "unamused face", shortcode: "unamused", keywords: &["meh", "annoyed"], category: Category::Smileys },
    Entry { ch: "🙄", name: "face with rolling eyes", shortcode: "roll_eyes", keywords: &["annoyed"], category: Category::Smileys },
    Entry { ch: "😬", name: "grimacing face", shortcode: "grimacing", keywords: &["awkward"], category: Category::Smileys },
    Entry { ch: "🤥", name: "lying face", shortcode: "lying_face", keywords: &["pinocchio", "liar"], category: Category::Smileys },
    Entry { ch: "😌", name: "relieved face", shortcode: "relieved", keywords: &["calm"], category: Category::Smileys },
    Entry { ch: "😔", name: "pensive face", shortcode: "pensive", keywords: &["sad", "thought"], category: Category::Smileys },
    Entry { ch: "😪", name: "sleepy face", shortcode: "sleepy", keywords: &["tired"], category: Category::Smileys },
    Entry { ch: "🤤", name: "drooling face", shortcode: "drooling_face", keywords: &["drool"], category: Category::Smileys },
    Entry { ch: "😴", name: "sleeping face", shortcode: "sleeping", keywords: &["zzz"], category: Category::Smileys },
    Entry { ch: "😷", name: "face with medical mask", shortcode: "mask", keywords: &["sick", "ill"], category: Category::Smileys },
    Entry { ch: "🤒", name: "face with thermometer", shortcode: "face_with_thermometer", keywords: &["sick", "fever"], category: Category::Smileys },
    Entry { ch: "🤕", name: "face with head-bandage", shortcode: "face_with_head_bandage", keywords: &["hurt", "injured"], category: Category::Smileys },
    Entry { ch: "🤢", name: "nauseated face", shortcode: "nauseated_face", keywords: &["sick", "yuck"], category: Category::Smileys },
    Entry { ch: "🤮", name: "face vomiting", shortcode: "vomiting_face", keywords: &["sick", "puke"], category: Category::Smileys },
    Entry { ch: "🤧", name: "sneezing face", shortcode: "sneezing_face", keywords: &["achoo", "allergy"], category: Category::Smileys },
    Entry { ch: "🥵", name: "hot face", shortcode: "hot_face", keywords: &["heat"], category: Category::Smileys },
    Entry { ch: "🥶", name: "cold face", shortcode: "cold_face", keywords: &["freezing"], category: Category::Smileys },
    Entry { ch: "🥴", name: "woozy face", shortcode: "woozy_face", keywords: &["drunk", "dizzy"], category: Category::Smileys },
    Entry { ch: "😵", name: "knocked-out face", shortcode: "dizzy_face", keywords: &["dizzy"], category: Category::Smileys },
    Entry { ch: "🤯", name: "exploding head", shortcode: "exploding_head", keywords: &["mind", "blown"], category: Category::Smileys },
    Entry { ch: "🤠", name: "cowboy hat face", shortcode: "cowboy_hat_face", keywords: &["yeehaw"], category: Category::Smileys },
    Entry { ch: "🥳", name: "partying face", shortcode: "partying_face", keywords: &["party", "celebrate"], category: Category::Smileys },
    Entry { ch: "🥸", name: "disguised face", shortcode: "disguised_face", keywords: &["incognito"], category: Category::Smileys },
    Entry { ch: "😎", name: "smiling face with sunglasses", shortcode: "sunglasses", keywords: &["cool"], category: Category::Smileys },
    Entry { ch: "🤓", name: "nerd face", shortcode: "nerd_face", keywords: &["geek", "glasses"], category: Category::Smileys },
    Entry { ch: "🧐", name: "face with monocle", shortcode: "monocle_face", keywords: &["inspect"], category: Category::Smileys },
    Entry { ch: "😕", name: "confused face", shortcode: "confused", keywords: &["puzzled"], category: Category::Smileys },
    Entry { ch: "😟", name: "worried face", shortcode: "worried", keywords: &["concern"], category: Category::Smileys },
    Entry { ch: "🙁", name: "slightly frowning face", shortcode: "slightly_frowning_face", keywords: &["sad"], category: Category::Smileys },
    Entry { ch: "😮", name: "face with open mouth", shortcode: "open_mouth", keywords: &["surprise"], category: Category::Smileys },
    Entry { ch: "😯", name: "hushed face", shortcode: "hushed", keywords: &["surprise"], category: Category::Smileys },
    Entry { ch: "😲", name: "astonished face", shortcode: "astonished", keywords: &["shocked"], category: Category::Smileys },
    Entry { ch: "😳", name: "flushed face", shortcode: "flushed", keywords: &["embarrass", "blush"], category: Category::Smileys },
    Entry { ch: "🥺", name: "pleading face", shortcode: "pleading_face", keywords: &["please", "puppy"], category: Category::Smileys },
    Entry { ch: "😦", name: "frowning face with open mouth", shortcode: "frowning", keywords: &["worried"], category: Category::Smileys },
    Entry { ch: "😧", name: "anguished face", shortcode: "anguished", keywords: &["shocked"], category: Category::Smileys },
    Entry { ch: "😨", name: "fearful face", shortcode: "fearful", keywords: &["scared"], category: Category::Smileys },
    Entry { ch: "😰", name: "anxious face with sweat", shortcode: "cold_sweat", keywords: &["nervous"], category: Category::Smileys },
    Entry { ch: "😥", name: "sad but relieved face", shortcode: "disappointed_relieved", keywords: &["sad"], category: Category::Smileys },
    Entry { ch: "😢", name: "crying face", shortcode: "cry", keywords: &["sad", "tear"], category: Category::Smileys },
    Entry { ch: "😭", name: "loudly crying face", shortcode: "sob", keywords: &["cry", "tears"], category: Category::Smileys },
    Entry { ch: "😱", name: "face screaming in fear", shortcode: "scream", keywords: &["munch", "horror"], category: Category::Smileys },
    Entry { ch: "😖", name: "confounded face", shortcode: "confounded", keywords: &["frustrated"], category: Category::Smileys },
    Entry { ch: "😣", name: "persevering face", shortcode: "persevere", keywords: &["struggling"], category: Category::Smileys },
    Entry { ch: "😞", name: "disappointed face", shortcode: "disappointed", keywords: &["sad"], category: Category::Smileys },
    Entry { ch: "😓", name: "downcast face with sweat", shortcode: "sweat", keywords: &["tired"], category: Category::Smileys },
    Entry { ch: "😩", name: "weary face", shortcode: "weary", keywords: &["tired"], category: Category::Smileys },
    Entry { ch: "😫", name: "tired face", shortcode: "tired_face", keywords: &["exhausted"], category: Category::Smileys },
    Entry { ch: "🥱", name: "yawning face", shortcode: "yawning_face", keywords: &["tired", "sleepy"], category: Category::Smileys },
    Entry { ch: "😤", name: "face with steam from nose", shortcode: "triumph", keywords: &["mad"], category: Category::Smileys },
    Entry { ch: "😡", name: "pouting face", shortcode: "rage", keywords: &["angry"], category: Category::Smileys },
    Entry { ch: "😠", name: "angry face", shortcode: "angry", keywords: &["mad"], category: Category::Smileys },
    Entry { ch: "🤬", name: "face with symbols on mouth", shortcode: "cursing_face", keywords: &["swear", "angry"], category: Category::Smileys },
    Entry { ch: "😈", name: "smiling face with horns", shortcode: "smiling_imp", keywords: &["devil"], category: Category::Smileys },
    Entry { ch: "👿", name: "angry face with horns", shortcode: "imp", keywords: &["devil"], category: Category::Smileys },
    Entry { ch: "💀", name: "skull", shortcode: "skull", keywords: &["death", "dead"], category: Category::Smileys },
    Entry { ch: "☠️", name: "skull and crossbones", shortcode: "skull_and_crossbones", keywords: &["poison", "death"], category: Category::Smileys },
    Entry { ch: "💩", name: "pile of poo", shortcode: "poop", keywords: &["shit", "crap"], category: Category::Smileys },
    Entry { ch: "🤡", name: "clown face", shortcode: "clown_face", keywords: &["joker"], category: Category::Smileys },
    Entry { ch: "👹", name: "ogre", shortcode: "japanese_ogre", keywords: &["monster"], category: Category::Smileys },
    Entry { ch: "👺", name: "goblin", shortcode: "japanese_goblin", keywords: &["monster"], category: Category::Smileys },
    Entry { ch: "👻", name: "ghost", shortcode: "ghost", keywords: &["boo", "spooky"], category: Category::Smileys },
    Entry { ch: "👽", name: "alien", shortcode: "alien", keywords: &["ufo"], category: Category::Smileys },
    Entry { ch: "🤖", name: "robot", shortcode: "robot", keywords: &["bot", "ai"], category: Category::Smileys },

    // ── people / gestures ──
    Entry { ch: "👋", name: "waving hand", shortcode: "wave", keywords: &["hi", "hello", "bye"], category: Category::People },
    Entry { ch: "🤚", name: "raised back of hand", shortcode: "raised_back_of_hand", keywords: &["stop"], category: Category::People },
    Entry { ch: "✋", name: "raised hand", shortcode: "hand", keywords: &["stop", "high five"], category: Category::People },
    Entry { ch: "🖖", name: "vulcan salute", shortcode: "vulcan_salute", keywords: &["spock", "trek"], category: Category::People },
    Entry { ch: "👌", name: "OK hand", shortcode: "ok_hand", keywords: &["okay", "perfect"], category: Category::People },
    Entry { ch: "🤌", name: "pinched fingers", shortcode: "pinched_fingers", keywords: &["italian"], category: Category::People },
    Entry { ch: "🤏", name: "pinching hand", shortcode: "pinching_hand", keywords: &["small", "tiny"], category: Category::People },
    Entry { ch: "✌️", name: "victory hand", shortcode: "v", keywords: &["peace", "victory"], category: Category::People },
    Entry { ch: "🤞", name: "crossed fingers", shortcode: "crossed_fingers", keywords: &["luck"], category: Category::People },
    Entry { ch: "🤟", name: "love-you gesture", shortcode: "love_you_gesture", keywords: &["ily"], category: Category::People },
    Entry { ch: "🤘", name: "sign of the horns", shortcode: "metal", keywords: &["rock"], category: Category::People },
    Entry { ch: "🤙", name: "call me hand", shortcode: "call_me_hand", keywords: &["shaka", "hang loose"], category: Category::People },
    Entry { ch: "👈", name: "backhand index pointing left", shortcode: "point_left", keywords: &["arrow"], category: Category::People },
    Entry { ch: "👉", name: "backhand index pointing right", shortcode: "point_right", keywords: &["arrow"], category: Category::People },
    Entry { ch: "👆", name: "backhand index pointing up", shortcode: "point_up_2", keywords: &["arrow"], category: Category::People },
    Entry { ch: "👇", name: "backhand index pointing down", shortcode: "point_down", keywords: &["arrow"], category: Category::People },
    Entry { ch: "☝️", name: "index pointing up", shortcode: "point_up", keywords: &["one"], category: Category::People },
    Entry { ch: "👍", name: "thumbs up", shortcode: "thumbsup", keywords: &["yes", "approve", "+1"], category: Category::People },
    Entry { ch: "👎", name: "thumbs down", shortcode: "thumbsdown", keywords: &["no", "disapprove", "-1"], category: Category::People },
    Entry { ch: "✊", name: "raised fist", shortcode: "fist_raised", keywords: &["power"], category: Category::People },
    Entry { ch: "👊", name: "oncoming fist", shortcode: "fist_oncoming", keywords: &["punch", "bro"], category: Category::People },
    Entry { ch: "🤛", name: "left-facing fist", shortcode: "fist_left", keywords: &["punch"], category: Category::People },
    Entry { ch: "🤜", name: "right-facing fist", shortcode: "fist_right", keywords: &["punch"], category: Category::People },
    Entry { ch: "👏", name: "clapping hands", shortcode: "clap", keywords: &["applause", "bravo"], category: Category::People },
    Entry { ch: "🙌", name: "raising hands", shortcode: "raised_hands", keywords: &["praise", "celebrate"], category: Category::People },
    Entry { ch: "👐", name: "open hands", shortcode: "open_hands", keywords: &["hug"], category: Category::People },
    Entry { ch: "🤲", name: "palms up together", shortcode: "palms_up_together", keywords: &["pray"], category: Category::People },
    Entry { ch: "🤝", name: "handshake", shortcode: "handshake", keywords: &["deal"], category: Category::People },
    Entry { ch: "🙏", name: "folded hands", shortcode: "pray", keywords: &["thanks", "please"], category: Category::People },
    Entry { ch: "💅", name: "nail polish", shortcode: "nail_care", keywords: &["manicure"], category: Category::People },
    Entry { ch: "🤳", name: "selfie", shortcode: "selfie", keywords: &["camera"], category: Category::People },
    Entry { ch: "💪", name: "flexed biceps", shortcode: "muscle", keywords: &["strong"], category: Category::People },
    Entry { ch: "🧠", name: "brain", shortcode: "brain", keywords: &["smart", "think"], category: Category::People },
    Entry { ch: "👀", name: "eyes", shortcode: "eyes", keywords: &["look", "watching"], category: Category::People },
    Entry { ch: "👁️", name: "eye", shortcode: "eye", keywords: &["look"], category: Category::People },
    Entry { ch: "👂", name: "ear", shortcode: "ear", keywords: &["listen"], category: Category::People },
    Entry { ch: "👃", name: "nose", shortcode: "nose", keywords: &["smell"], category: Category::People },
    Entry { ch: "👄", name: "mouth", shortcode: "lips", keywords: &["kiss"], category: Category::People },
    Entry { ch: "👶", name: "baby", shortcode: "baby", keywords: &["child"], category: Category::People },
    Entry { ch: "🧒", name: "child", shortcode: "child", keywords: &["kid"], category: Category::People },
    Entry { ch: "👦", name: "boy", shortcode: "boy", keywords: &["male"], category: Category::People },
    Entry { ch: "👧", name: "girl", shortcode: "girl", keywords: &["female"], category: Category::People },
    Entry { ch: "👨", name: "man", shortcode: "man", keywords: &["male"], category: Category::People },
    Entry { ch: "👩", name: "woman", shortcode: "woman", keywords: &["female"], category: Category::People },
    Entry { ch: "🧑", name: "person", shortcode: "person", keywords: &["adult"], category: Category::People },
    Entry { ch: "👴", name: "old man", shortcode: "older_man", keywords: &["elder"], category: Category::People },
    Entry { ch: "👵", name: "old woman", shortcode: "older_woman", keywords: &["elder"], category: Category::People },
    Entry { ch: "🧔", name: "person with beard", shortcode: "bearded_person", keywords: &["man"], category: Category::People },
    Entry { ch: "🤰", name: "pregnant woman", shortcode: "pregnant_woman", keywords: &["baby"], category: Category::People },

    // ── animals ──
    Entry { ch: "🐶", name: "dog face", shortcode: "dog", keywords: &["puppy", "pet"], category: Category::Animals },
    Entry { ch: "🐱", name: "cat face", shortcode: "cat", keywords: &["kitten", "pet"], category: Category::Animals },
    Entry { ch: "🐭", name: "mouse face", shortcode: "mouse", keywords: &["rodent"], category: Category::Animals },
    Entry { ch: "🐹", name: "hamster", shortcode: "hamster", keywords: &["pet"], category: Category::Animals },
    Entry { ch: "🐰", name: "rabbit face", shortcode: "rabbit", keywords: &["bunny"], category: Category::Animals },
    Entry { ch: "🦊", name: "fox", shortcode: "fox_face", keywords: &["foxy"], category: Category::Animals },
    Entry { ch: "🐻", name: "bear", shortcode: "bear", keywords: &["teddy"], category: Category::Animals },
    Entry { ch: "🐼", name: "panda", shortcode: "panda_face", keywords: &["bear"], category: Category::Animals },
    Entry { ch: "🐨", name: "koala", shortcode: "koala", keywords: &["bear"], category: Category::Animals },
    Entry { ch: "🐯", name: "tiger face", shortcode: "tiger", keywords: &["cat"], category: Category::Animals },
    Entry { ch: "🦁", name: "lion", shortcode: "lion", keywords: &["roar"], category: Category::Animals },
    Entry { ch: "🐮", name: "cow face", shortcode: "cow", keywords: &["moo"], category: Category::Animals },
    Entry { ch: "🐷", name: "pig face", shortcode: "pig", keywords: &["oink"], category: Category::Animals },
    Entry { ch: "🐸", name: "frog", shortcode: "frog", keywords: &["pepe"], category: Category::Animals },
    Entry { ch: "🐵", name: "monkey face", shortcode: "monkey_face", keywords: &["ape"], category: Category::Animals },
    Entry { ch: "🙈", name: "see-no-evil monkey", shortcode: "see_no_evil", keywords: &["monkey"], category: Category::Animals },
    Entry { ch: "🙉", name: "hear-no-evil monkey", shortcode: "hear_no_evil", keywords: &["monkey"], category: Category::Animals },
    Entry { ch: "🙊", name: "speak-no-evil monkey", shortcode: "speak_no_evil", keywords: &["monkey"], category: Category::Animals },
    Entry { ch: "🐔", name: "chicken", shortcode: "chicken", keywords: &["bird"], category: Category::Animals },
    Entry { ch: "🐧", name: "penguin", shortcode: "penguin", keywords: &["bird"], category: Category::Animals },
    Entry { ch: "🐦", name: "bird", shortcode: "bird", keywords: &["tweet"], category: Category::Animals },
    Entry { ch: "🦆", name: "duck", shortcode: "duck", keywords: &["bird"], category: Category::Animals },
    Entry { ch: "🦅", name: "eagle", shortcode: "eagle", keywords: &["bird"], category: Category::Animals },
    Entry { ch: "🦉", name: "owl", shortcode: "owl", keywords: &["bird", "wise"], category: Category::Animals },
    Entry { ch: "🐺", name: "wolf", shortcode: "wolf", keywords: &["howl"], category: Category::Animals },
    Entry { ch: "🐴", name: "horse face", shortcode: "horse", keywords: &["pony"], category: Category::Animals },
    Entry { ch: "🦄", name: "unicorn", shortcode: "unicorn", keywords: &["mythical"], category: Category::Animals },
    Entry { ch: "🐝", name: "honeybee", shortcode: "bee", keywords: &["buzz"], category: Category::Animals },
    Entry { ch: "🐛", name: "bug", shortcode: "bug", keywords: &["insect"], category: Category::Animals },
    Entry { ch: "🦋", name: "butterfly", shortcode: "butterfly", keywords: &["insect"], category: Category::Animals },
    Entry { ch: "🐌", name: "snail", shortcode: "snail", keywords: &["slow"], category: Category::Animals },
    Entry { ch: "🐞", name: "lady beetle", shortcode: "lady_beetle", keywords: &["bug"], category: Category::Animals },
    Entry { ch: "🕷️", name: "spider", shortcode: "spider", keywords: &["bug"], category: Category::Animals },
    Entry { ch: "🦂", name: "scorpion", shortcode: "scorpion", keywords: &["bug"], category: Category::Animals },
    Entry { ch: "🐢", name: "turtle", shortcode: "turtle", keywords: &["slow"], category: Category::Animals },
    Entry { ch: "🐍", name: "snake", shortcode: "snake", keywords: &["python"], category: Category::Animals },
    Entry { ch: "🦖", name: "T-Rex", shortcode: "t_rex", keywords: &["dinosaur"], category: Category::Animals },
    Entry { ch: "🐙", name: "octopus", shortcode: "octopus", keywords: &["sea"], category: Category::Animals },
    Entry { ch: "🦑", name: "squid", shortcode: "squid", keywords: &["sea"], category: Category::Animals },
    Entry { ch: "🦀", name: "crab", shortcode: "crab", keywords: &["sea"], category: Category::Animals },
    Entry { ch: "🐠", name: "tropical fish", shortcode: "tropical_fish", keywords: &["sea"], category: Category::Animals },
    Entry { ch: "🐟", name: "fish", shortcode: "fish", keywords: &["sea"], category: Category::Animals },
    Entry { ch: "🐬", name: "dolphin", shortcode: "dolphin", keywords: &["sea"], category: Category::Animals },
    Entry { ch: "🐳", name: "spouting whale", shortcode: "whale", keywords: &["sea"], category: Category::Animals },
    Entry { ch: "🦈", name: "shark", shortcode: "shark", keywords: &["sea"], category: Category::Animals },
    Entry { ch: "🌵", name: "cactus", shortcode: "cactus", keywords: &["plant"], category: Category::Animals },
    Entry { ch: "🌲", name: "evergreen tree", shortcode: "evergreen_tree", keywords: &["tree"], category: Category::Animals },
    Entry { ch: "🌳", name: "deciduous tree", shortcode: "deciduous_tree", keywords: &["tree"], category: Category::Animals },
    Entry { ch: "🌴", name: "palm tree", shortcode: "palm_tree", keywords: &["tree"], category: Category::Animals },
    Entry { ch: "🌱", name: "seedling", shortcode: "seedling", keywords: &["plant"], category: Category::Animals },
    Entry { ch: "🌿", name: "herb", shortcode: "herb", keywords: &["plant", "leaf"], category: Category::Animals },
    Entry { ch: "🍀", name: "four leaf clover", shortcode: "four_leaf_clover", keywords: &["luck"], category: Category::Animals },
    Entry { ch: "🍃", name: "leaf fluttering in wind", shortcode: "leaves", keywords: &["plant"], category: Category::Animals },
    Entry { ch: "🌹", name: "rose", shortcode: "rose", keywords: &["flower"], category: Category::Animals },
    Entry { ch: "🌷", name: "tulip", shortcode: "tulip", keywords: &["flower"], category: Category::Animals },
    Entry { ch: "🌼", name: "blossom", shortcode: "blossom", keywords: &["flower"], category: Category::Animals },
    Entry { ch: "🌸", name: "cherry blossom", shortcode: "cherry_blossom", keywords: &["sakura"], category: Category::Animals },
    Entry { ch: "🌻", name: "sunflower", shortcode: "sunflower", keywords: &["flower"], category: Category::Animals },

    // ── food ──
    Entry { ch: "🍎", name: "red apple", shortcode: "apple", keywords: &["fruit"], category: Category::Food },
    Entry { ch: "🍏", name: "green apple", shortcode: "green_apple", keywords: &["fruit"], category: Category::Food },
    Entry { ch: "🍐", name: "pear", shortcode: "pear", keywords: &["fruit"], category: Category::Food },
    Entry { ch: "🍊", name: "tangerine", shortcode: "tangerine", keywords: &["fruit", "orange"], category: Category::Food },
    Entry { ch: "🍋", name: "lemon", shortcode: "lemon", keywords: &["fruit"], category: Category::Food },
    Entry { ch: "🍌", name: "banana", shortcode: "banana", keywords: &["fruit"], category: Category::Food },
    Entry { ch: "🍉", name: "watermelon", shortcode: "watermelon", keywords: &["fruit"], category: Category::Food },
    Entry { ch: "🍇", name: "grapes", shortcode: "grapes", keywords: &["fruit", "wine"], category: Category::Food },
    Entry { ch: "🍓", name: "strawberry", shortcode: "strawberry", keywords: &["fruit"], category: Category::Food },
    Entry { ch: "🫐", name: "blueberries", shortcode: "blueberries", keywords: &["fruit"], category: Category::Food },
    Entry { ch: "🍈", name: "melon", shortcode: "melon", keywords: &["fruit"], category: Category::Food },
    Entry { ch: "🍒", name: "cherries", shortcode: "cherries", keywords: &["fruit"], category: Category::Food },
    Entry { ch: "🍑", name: "peach", shortcode: "peach", keywords: &["fruit", "butt"], category: Category::Food },
    Entry { ch: "🥭", name: "mango", shortcode: "mango", keywords: &["fruit"], category: Category::Food },
    Entry { ch: "🍍", name: "pineapple", shortcode: "pineapple", keywords: &["fruit"], category: Category::Food },
    Entry { ch: "🥥", name: "coconut", shortcode: "coconut", keywords: &["fruit"], category: Category::Food },
    Entry { ch: "🥝", name: "kiwi fruit", shortcode: "kiwi_fruit", keywords: &["fruit"], category: Category::Food },
    Entry { ch: "🍅", name: "tomato", shortcode: "tomato", keywords: &["fruit", "veg"], category: Category::Food },
    Entry { ch: "🍆", name: "eggplant", shortcode: "eggplant", keywords: &["aubergine"], category: Category::Food },
    Entry { ch: "🥑", name: "avocado", shortcode: "avocado", keywords: &["fruit"], category: Category::Food },
    Entry { ch: "🥦", name: "broccoli", shortcode: "broccoli", keywords: &["vegetable"], category: Category::Food },
    Entry { ch: "🥕", name: "carrot", shortcode: "carrot", keywords: &["vegetable"], category: Category::Food },
    Entry { ch: "🌽", name: "ear of corn", shortcode: "corn", keywords: &["maize"], category: Category::Food },
    Entry { ch: "🌶️", name: "hot pepper", shortcode: "hot_pepper", keywords: &["spicy", "chili"], category: Category::Food },
    Entry { ch: "🫑", name: "bell pepper", shortcode: "bell_pepper", keywords: &["vegetable"], category: Category::Food },
    Entry { ch: "🥒", name: "cucumber", shortcode: "cucumber", keywords: &["vegetable"], category: Category::Food },
    Entry { ch: "🥬", name: "leafy green", shortcode: "leafy_greens", keywords: &["lettuce"], category: Category::Food },
    Entry { ch: "🥔", name: "potato", shortcode: "potato", keywords: &["vegetable"], category: Category::Food },
    Entry { ch: "🍞", name: "bread", shortcode: "bread", keywords: &["loaf"], category: Category::Food },
    Entry { ch: "🥐", name: "croissant", shortcode: "croissant", keywords: &["bread"], category: Category::Food },
    Entry { ch: "🥖", name: "baguette bread", shortcode: "baguette_bread", keywords: &["bread"], category: Category::Food },
    Entry { ch: "🧀", name: "cheese wedge", shortcode: "cheese", keywords: &["dairy"], category: Category::Food },
    Entry { ch: "🥚", name: "egg", shortcode: "egg", keywords: &["breakfast"], category: Category::Food },
    Entry { ch: "🍳", name: "cooking", shortcode: "fried_egg", keywords: &["egg", "breakfast"], category: Category::Food },
    Entry { ch: "🥓", name: "bacon", shortcode: "bacon", keywords: &["meat"], category: Category::Food },
    Entry { ch: "🍔", name: "hamburger", shortcode: "hamburger", keywords: &["burger"], category: Category::Food },
    Entry { ch: "🍟", name: "french fries", shortcode: "fries", keywords: &["chips"], category: Category::Food },
    Entry { ch: "🍕", name: "pizza", shortcode: "pizza", keywords: &["italian"], category: Category::Food },
    Entry { ch: "🌭", name: "hot dog", shortcode: "hotdog", keywords: &["sausage"], category: Category::Food },
    Entry { ch: "🌮", name: "taco", shortcode: "taco", keywords: &["mexican"], category: Category::Food },
    Entry { ch: "🌯", name: "burrito", shortcode: "burrito", keywords: &["mexican"], category: Category::Food },
    Entry { ch: "🥙", name: "stuffed flatbread", shortcode: "stuffed_flatbread", keywords: &["kebab"], category: Category::Food },
    Entry { ch: "🥗", name: "green salad", shortcode: "green_salad", keywords: &["healthy"], category: Category::Food },
    Entry { ch: "🍝", name: "spaghetti", shortcode: "spaghetti", keywords: &["pasta"], category: Category::Food },
    Entry { ch: "🍜", name: "steaming bowl", shortcode: "ramen", keywords: &["noodles"], category: Category::Food },
    Entry { ch: "🍣", name: "sushi", shortcode: "sushi", keywords: &["japanese"], category: Category::Food },
    Entry { ch: "🍱", name: "bento box", shortcode: "bento", keywords: &["japanese"], category: Category::Food },
    Entry { ch: "🍤", name: "fried shrimp", shortcode: "fried_shrimp", keywords: &["seafood"], category: Category::Food },
    Entry { ch: "🍙", name: "rice ball", shortcode: "rice_ball", keywords: &["japanese"], category: Category::Food },
    Entry { ch: "🍰", name: "shortcake", shortcode: "cake", keywords: &["dessert"], category: Category::Food },
    Entry { ch: "🎂", name: "birthday cake", shortcode: "birthday", keywords: &["cake", "bday"], category: Category::Food },
    Entry { ch: "🍪", name: "cookie", shortcode: "cookie", keywords: &["biscuit"], category: Category::Food },
    Entry { ch: "🍩", name: "doughnut", shortcode: "doughnut", keywords: &["donut"], category: Category::Food },
    Entry { ch: "🍫", name: "chocolate bar", shortcode: "chocolate_bar", keywords: &["sweet"], category: Category::Food },
    Entry { ch: "🍬", name: "candy", shortcode: "candy", keywords: &["sweet"], category: Category::Food },
    Entry { ch: "🍭", name: "lollipop", shortcode: "lollipop", keywords: &["sweet"], category: Category::Food },
    Entry { ch: "🍿", name: "popcorn", shortcode: "popcorn", keywords: &["movie"], category: Category::Food },
    Entry { ch: "🍦", name: "soft ice cream", shortcode: "icecream", keywords: &["dessert"], category: Category::Food },
    Entry { ch: "🍨", name: "ice cream", shortcode: "ice_cream", keywords: &["dessert"], category: Category::Food },
    Entry { ch: "☕", name: "hot beverage", shortcode: "coffee", keywords: &["caffeine"], category: Category::Food },
    Entry { ch: "🍵", name: "teacup without handle", shortcode: "tea", keywords: &["matcha"], category: Category::Food },
    Entry { ch: "🍺", name: "beer mug", shortcode: "beer", keywords: &["drink"], category: Category::Food },
    Entry { ch: "🍻", name: "clinking beer mugs", shortcode: "beers", keywords: &["cheers"], category: Category::Food },
    Entry { ch: "🥂", name: "clinking glasses", shortcode: "clinking_glasses", keywords: &["champagne", "cheers"], category: Category::Food },
    Entry { ch: "🍷", name: "wine glass", shortcode: "wine_glass", keywords: &["drink"], category: Category::Food },
    Entry { ch: "🍸", name: "cocktail glass", shortcode: "cocktail", keywords: &["martini"], category: Category::Food },
    Entry { ch: "🍹", name: "tropical drink", shortcode: "tropical_drink", keywords: &["cocktail"], category: Category::Food },
    Entry { ch: "🥃", name: "tumbler glass", shortcode: "tumbler_glass", keywords: &["whiskey"], category: Category::Food },
    Entry { ch: "🍾", name: "bottle with popping cork", shortcode: "champagne", keywords: &["celebrate"], category: Category::Food },

    // ── activities ──
    Entry { ch: "⚽", name: "soccer ball", shortcode: "soccer", keywords: &["football", "ball"], category: Category::Activities },
    Entry { ch: "🏀", name: "basketball", shortcode: "basketball", keywords: &["ball"], category: Category::Activities },
    Entry { ch: "🏈", name: "american football", shortcode: "football", keywords: &["ball"], category: Category::Activities },
    Entry { ch: "⚾", name: "baseball", shortcode: "baseball", keywords: &["ball"], category: Category::Activities },
    Entry { ch: "🎾", name: "tennis", shortcode: "tennis", keywords: &["ball"], category: Category::Activities },
    Entry { ch: "🏐", name: "volleyball", shortcode: "volleyball", keywords: &["ball"], category: Category::Activities },
    Entry { ch: "🏉", name: "rugby football", shortcode: "rugby_football", keywords: &["ball"], category: Category::Activities },
    Entry { ch: "🎱", name: "pool 8 ball", shortcode: "8ball", keywords: &["billiards"], category: Category::Activities },
    Entry { ch: "🏓", name: "ping pong", shortcode: "ping_pong", keywords: &["paddle"], category: Category::Activities },
    Entry { ch: "🏸", name: "badminton", shortcode: "badminton", keywords: &["racket"], category: Category::Activities },
    Entry { ch: "🥊", name: "boxing glove", shortcode: "boxing_glove", keywords: &["fight"], category: Category::Activities },
    Entry { ch: "🏊", name: "person swimming", shortcode: "swimmer", keywords: &["swim"], category: Category::Activities },
    Entry { ch: "🚴", name: "person biking", shortcode: "bicyclist", keywords: &["bike"], category: Category::Activities },
    Entry { ch: "🏃", name: "person running", shortcode: "runner", keywords: &["run"], category: Category::Activities },
    Entry { ch: "🚶", name: "person walking", shortcode: "walking", keywords: &["walk"], category: Category::Activities },
    Entry { ch: "🎯", name: "bullseye", shortcode: "dart", keywords: &["target"], category: Category::Activities },
    Entry { ch: "🎮", name: "video game", shortcode: "video_game", keywords: &["controller", "play"], category: Category::Activities },
    Entry { ch: "🎲", name: "game die", shortcode: "game_die", keywords: &["dice"], category: Category::Activities },
    Entry { ch: "🎰", name: "slot machine", shortcode: "slot_machine", keywords: &["gamble"], category: Category::Activities },
    Entry { ch: "🎼", name: "musical score", shortcode: "musical_score", keywords: &["music"], category: Category::Activities },
    Entry { ch: "🎵", name: "musical note", shortcode: "musical_note", keywords: &["music"], category: Category::Activities },
    Entry { ch: "🎶", name: "musical notes", shortcode: "notes", keywords: &["music"], category: Category::Activities },
    Entry { ch: "🎤", name: "microphone", shortcode: "microphone", keywords: &["mic", "sing"], category: Category::Activities },
    Entry { ch: "🎧", name: "headphone", shortcode: "headphones", keywords: &["music"], category: Category::Activities },
    Entry { ch: "🎸", name: "guitar", shortcode: "guitar", keywords: &["music"], category: Category::Activities },
    Entry { ch: "🎹", name: "musical keyboard", shortcode: "musical_keyboard", keywords: &["piano"], category: Category::Activities },
    Entry { ch: "🥁", name: "drum", shortcode: "drum", keywords: &["music"], category: Category::Activities },
    Entry { ch: "🎉", name: "party popper", shortcode: "tada", keywords: &["party", "celebrate"], category: Category::Activities },
    Entry { ch: "🎊", name: "confetti ball", shortcode: "confetti_ball", keywords: &["party"], category: Category::Activities },
    Entry { ch: "🎈", name: "balloon", shortcode: "balloon", keywords: &["party"], category: Category::Activities },
    Entry { ch: "🎁", name: "wrapped gift", shortcode: "gift", keywords: &["present"], category: Category::Activities },
    Entry { ch: "🎄", name: "christmas tree", shortcode: "christmas_tree", keywords: &["xmas"], category: Category::Activities },
    Entry { ch: "🎃", name: "jack-o-lantern", shortcode: "jack_o_lantern", keywords: &["halloween", "pumpkin"], category: Category::Activities },
    Entry { ch: "🏆", name: "trophy", shortcode: "trophy", keywords: &["win"], category: Category::Activities },
    Entry { ch: "🥇", name: "1st place medal", shortcode: "1st_place_medal", keywords: &["gold"], category: Category::Activities },
    Entry { ch: "🥈", name: "2nd place medal", shortcode: "2nd_place_medal", keywords: &["silver"], category: Category::Activities },
    Entry { ch: "🥉", name: "3rd place medal", shortcode: "3rd_place_medal", keywords: &["bronze"], category: Category::Activities },
    Entry { ch: "🎖️", name: "military medal", shortcode: "medal_military", keywords: &["award"], category: Category::Activities },

    // ── travel ──
    Entry { ch: "🚗", name: "automobile", shortcode: "car", keywords: &["vehicle"], category: Category::Travel },
    Entry { ch: "🚕", name: "taxi", shortcode: "taxi", keywords: &["cab"], category: Category::Travel },
    Entry { ch: "🚙", name: "sport utility vehicle", shortcode: "blue_car", keywords: &["suv"], category: Category::Travel },
    Entry { ch: "🚌", name: "bus", shortcode: "bus", keywords: &["transport"], category: Category::Travel },
    Entry { ch: "🚎", name: "trolleybus", shortcode: "trolleybus", keywords: &["transport"], category: Category::Travel },
    Entry { ch: "🚓", name: "police car", shortcode: "police_car", keywords: &["cops"], category: Category::Travel },
    Entry { ch: "🚑", name: "ambulance", shortcode: "ambulance", keywords: &["medical"], category: Category::Travel },
    Entry { ch: "🚒", name: "fire engine", shortcode: "fire_engine", keywords: &["fire"], category: Category::Travel },
    Entry { ch: "🚜", name: "tractor", shortcode: "tractor", keywords: &["farm"], category: Category::Travel },
    Entry { ch: "🏍️", name: "motorcycle", shortcode: "motorcycle", keywords: &["bike"], category: Category::Travel },
    Entry { ch: "🛵", name: "motor scooter", shortcode: "motor_scooter", keywords: &["vespa"], category: Category::Travel },
    Entry { ch: "🚲", name: "bicycle", shortcode: "bike", keywords: &["cycle"], category: Category::Travel },
    Entry { ch: "🛴", name: "kick scooter", shortcode: "kick_scooter", keywords: &["transport"], category: Category::Travel },
    Entry { ch: "🚂", name: "locomotive", shortcode: "steam_locomotive", keywords: &["train"], category: Category::Travel },
    Entry { ch: "🚀", name: "rocket", shortcode: "rocket", keywords: &["launch", "ship"], category: Category::Travel },
    Entry { ch: "🛸", name: "flying saucer", shortcode: "flying_saucer", keywords: &["ufo"], category: Category::Travel },
    Entry { ch: "🚁", name: "helicopter", shortcode: "helicopter", keywords: &["fly"], category: Category::Travel },
    Entry { ch: "✈️", name: "airplane", shortcode: "airplane", keywords: &["fly", "plane"], category: Category::Travel },
    Entry { ch: "⛵", name: "sailboat", shortcode: "sailboat", keywords: &["boat"], category: Category::Travel },
    Entry { ch: "🚤", name: "speedboat", shortcode: "speedboat", keywords: &["boat"], category: Category::Travel },
    Entry { ch: "🚢", name: "ship", shortcode: "ship", keywords: &["boat"], category: Category::Travel },
    Entry { ch: "⚓", name: "anchor", shortcode: "anchor", keywords: &["ship"], category: Category::Travel },
    Entry { ch: "🏠", name: "house", shortcode: "house", keywords: &["home"], category: Category::Travel },
    Entry { ch: "🏢", name: "office building", shortcode: "office", keywords: &["work"], category: Category::Travel },
    Entry { ch: "🏥", name: "hospital", shortcode: "hospital", keywords: &["medical"], category: Category::Travel },
    Entry { ch: "🏫", name: "school", shortcode: "school", keywords: &["education"], category: Category::Travel },
    Entry { ch: "🗽", name: "statue of liberty", shortcode: "statue_of_liberty", keywords: &["nyc"], category: Category::Travel },
    Entry { ch: "🗼", name: "tokyo tower", shortcode: "tokyo_tower", keywords: &["japan"], category: Category::Travel },
    Entry { ch: "🌅", name: "sunrise", shortcode: "sunrise", keywords: &["dawn"], category: Category::Travel },
    Entry { ch: "🌄", name: "sunrise over mountains", shortcode: "sunrise_over_mountains", keywords: &["dawn"], category: Category::Travel },
    Entry { ch: "🌃", name: "night with stars", shortcode: "night_with_stars", keywords: &["night"], category: Category::Travel },
    Entry { ch: "🌇", name: "sunset", shortcode: "city_sunset", keywords: &["dusk"], category: Category::Travel },
    Entry { ch: "🌈", name: "rainbow", shortcode: "rainbow", keywords: &["pride", "lgbt"], category: Category::Travel },
    Entry { ch: "🌊", name: "water wave", shortcode: "ocean", keywords: &["sea"], category: Category::Travel },
    Entry { ch: "🌋", name: "volcano", shortcode: "volcano", keywords: &["lava"], category: Category::Travel },
    Entry { ch: "⛰️", name: "mountain", shortcode: "mountain", keywords: &["peak"], category: Category::Travel },
    Entry { ch: "🏖️", name: "beach with umbrella", shortcode: "beach_umbrella", keywords: &["sand"], category: Category::Travel },
    Entry { ch: "🏝️", name: "desert island", shortcode: "desert_island", keywords: &["beach"], category: Category::Travel },

    // ── objects ──
    Entry { ch: "💡", name: "light bulb", shortcode: "bulb", keywords: &["idea"], category: Category::Objects },
    Entry { ch: "🔦", name: "flashlight", shortcode: "flashlight", keywords: &["torch"], category: Category::Objects },
    Entry { ch: "🕯️", name: "candle", shortcode: "candle", keywords: &["light"], category: Category::Objects },
    Entry { ch: "🔌", name: "electric plug", shortcode: "electric_plug", keywords: &["power"], category: Category::Objects },
    Entry { ch: "🔋", name: "battery", shortcode: "battery", keywords: &["power"], category: Category::Objects },
    Entry { ch: "📱", name: "mobile phone", shortcode: "iphone", keywords: &["phone"], category: Category::Objects },
    Entry { ch: "💻", name: "laptop", shortcode: "computer", keywords: &["pc", "mac"], category: Category::Objects },
    Entry { ch: "⌨️", name: "keyboard", shortcode: "keyboard", keywords: &["type"], category: Category::Objects },
    Entry { ch: "🖥️", name: "desktop computer", shortcode: "desktop_computer", keywords: &["pc"], category: Category::Objects },
    Entry { ch: "🖨️", name: "printer", shortcode: "printer", keywords: &["office"], category: Category::Objects },
    Entry { ch: "🖱️", name: "computer mouse", shortcode: "computer_mouse", keywords: &["click"], category: Category::Objects },
    Entry { ch: "💾", name: "floppy disk", shortcode: "floppy_disk", keywords: &["save"], category: Category::Objects },
    Entry { ch: "💿", name: "optical disk", shortcode: "cd", keywords: &["disc"], category: Category::Objects },
    Entry { ch: "📷", name: "camera", shortcode: "camera", keywords: &["photo"], category: Category::Objects },
    Entry { ch: "📸", name: "camera with flash", shortcode: "camera_flash", keywords: &["photo"], category: Category::Objects },
    Entry { ch: "📹", name: "video camera", shortcode: "video_camera", keywords: &["record"], category: Category::Objects },
    Entry { ch: "📺", name: "television", shortcode: "tv", keywords: &["screen"], category: Category::Objects },
    Entry { ch: "📻", name: "radio", shortcode: "radio", keywords: &["broadcast"], category: Category::Objects },
    Entry { ch: "📞", name: "telephone receiver", shortcode: "telephone_receiver", keywords: &["phone", "call"], category: Category::Objects },
    Entry { ch: "📟", name: "pager", shortcode: "pager", keywords: &["beeper"], category: Category::Objects },
    Entry { ch: "📠", name: "fax machine", shortcode: "fax", keywords: &["office"], category: Category::Objects },
    Entry { ch: "🔍", name: "magnifying glass tilted left", shortcode: "mag", keywords: &["search"], category: Category::Objects },
    Entry { ch: "🔎", name: "magnifying glass tilted right", shortcode: "mag_right", keywords: &["search"], category: Category::Objects },
    Entry { ch: "🔒", name: "locked", shortcode: "lock", keywords: &["secure"], category: Category::Objects },
    Entry { ch: "🔓", name: "unlocked", shortcode: "unlock", keywords: &["open"], category: Category::Objects },
    Entry { ch: "🔑", name: "key", shortcode: "key", keywords: &["lock"], category: Category::Objects },
    Entry { ch: "🔨", name: "hammer", shortcode: "hammer", keywords: &["tool"], category: Category::Objects },
    Entry { ch: "🪓", name: "axe", shortcode: "axe", keywords: &["tool"], category: Category::Objects },
    Entry { ch: "⚒️", name: "hammer and pick", shortcode: "hammer_and_pick", keywords: &["tool"], category: Category::Objects },
    Entry { ch: "🛠️", name: "hammer and wrench", shortcode: "hammer_and_wrench", keywords: &["tool"], category: Category::Objects },
    Entry { ch: "⚙️", name: "gear", shortcode: "gear", keywords: &["settings", "cog"], category: Category::Objects },
    Entry { ch: "🔧", name: "wrench", shortcode: "wrench", keywords: &["tool"], category: Category::Objects },
    Entry { ch: "🔩", name: "nut and bolt", shortcode: "nut_and_bolt", keywords: &["screw"], category: Category::Objects },
    Entry { ch: "🧪", name: "test tube", shortcode: "test_tube", keywords: &["science"], category: Category::Objects },
    Entry { ch: "🧫", name: "petri dish", shortcode: "petri_dish", keywords: &["science"], category: Category::Objects },
    Entry { ch: "💉", name: "syringe", shortcode: "syringe", keywords: &["needle", "vaccine"], category: Category::Objects },
    Entry { ch: "💊", name: "pill", shortcode: "pill", keywords: &["medicine"], category: Category::Objects },
    Entry { ch: "💰", name: "money bag", shortcode: "moneybag", keywords: &["cash"], category: Category::Objects },
    Entry { ch: "💵", name: "dollar banknote", shortcode: "dollar", keywords: &["money"], category: Category::Objects },
    Entry { ch: "💳", name: "credit card", shortcode: "credit_card", keywords: &["money"], category: Category::Objects },
    Entry { ch: "📚", name: "books", shortcode: "books", keywords: &["read", "library"], category: Category::Objects },
    Entry { ch: "📖", name: "open book", shortcode: "open_book", keywords: &["read"], category: Category::Objects },
    Entry { ch: "📝", name: "memo", shortcode: "memo", keywords: &["note", "write"], category: Category::Objects },
    Entry { ch: "✏️", name: "pencil", shortcode: "pencil2", keywords: &["write"], category: Category::Objects },
    Entry { ch: "✒️", name: "black nib", shortcode: "black_nib", keywords: &["pen"], category: Category::Objects },
    Entry { ch: "📎", name: "paperclip", shortcode: "paperclip", keywords: &["attach"], category: Category::Objects },
    Entry { ch: "📌", name: "pushpin", shortcode: "pushpin", keywords: &["pin"], category: Category::Objects },
    Entry { ch: "📍", name: "round pushpin", shortcode: "round_pushpin", keywords: &["location"], category: Category::Objects },
    Entry { ch: "📁", name: "file folder", shortcode: "file_folder", keywords: &["files"], category: Category::Objects },
    Entry { ch: "📂", name: "open file folder", shortcode: "open_file_folder", keywords: &["files"], category: Category::Objects },
    Entry { ch: "📅", name: "calendar", shortcode: "date", keywords: &["calendar"], category: Category::Objects },
    Entry { ch: "📆", name: "tear-off calendar", shortcode: "calendar", keywords: &["date"], category: Category::Objects },
    Entry { ch: "🗓️", name: "spiral calendar", shortcode: "spiral_calendar", keywords: &["date"], category: Category::Objects },
    Entry { ch: "📊", name: "bar chart", shortcode: "bar_chart", keywords: &["stats"], category: Category::Objects },
    Entry { ch: "📈", name: "chart increasing", shortcode: "chart_with_upwards_trend", keywords: &["growth"], category: Category::Objects },
    Entry { ch: "📉", name: "chart decreasing", shortcode: "chart_with_downwards_trend", keywords: &["loss"], category: Category::Objects },
    Entry { ch: "📰", name: "newspaper", shortcode: "newspaper", keywords: &["news"], category: Category::Objects },
    Entry { ch: "📦", name: "package", shortcode: "package", keywords: &["box"], category: Category::Objects },
    Entry { ch: "📧", name: "e-mail", shortcode: "email", keywords: &["mail"], category: Category::Objects },
    Entry { ch: "📨", name: "incoming envelope", shortcode: "incoming_envelope", keywords: &["mail"], category: Category::Objects },
    Entry { ch: "📬", name: "open mailbox with raised flag", shortcode: "mailbox_with_mail", keywords: &["mail"], category: Category::Objects },
    Entry { ch: "🔔", name: "bell", shortcode: "bell", keywords: &["alarm", "notify"], category: Category::Objects },
    Entry { ch: "🔕", name: "bell with slash", shortcode: "no_bell", keywords: &["mute"], category: Category::Objects },
    Entry { ch: "🎈", name: "balloon", shortcode: "balloon_obj", keywords: &["party"], category: Category::Objects },

    // ── symbols ──
    Entry { ch: "❤️", name: "red heart", shortcode: "heart", keywords: &["love"], category: Category::Symbols },
    Entry { ch: "🧡", name: "orange heart", shortcode: "orange_heart", keywords: &["love"], category: Category::Symbols },
    Entry { ch: "💛", name: "yellow heart", shortcode: "yellow_heart", keywords: &["love"], category: Category::Symbols },
    Entry { ch: "💚", name: "green heart", shortcode: "green_heart", keywords: &["love"], category: Category::Symbols },
    Entry { ch: "💙", name: "blue heart", shortcode: "blue_heart", keywords: &["love"], category: Category::Symbols },
    Entry { ch: "💜", name: "purple heart", shortcode: "purple_heart", keywords: &["love"], category: Category::Symbols },
    Entry { ch: "🖤", name: "black heart", shortcode: "black_heart", keywords: &["love"], category: Category::Symbols },
    Entry { ch: "🤍", name: "white heart", shortcode: "white_heart", keywords: &["love"], category: Category::Symbols },
    Entry { ch: "🤎", name: "brown heart", shortcode: "brown_heart", keywords: &["love"], category: Category::Symbols },
    Entry { ch: "💔", name: "broken heart", shortcode: "broken_heart", keywords: &["heartbreak"], category: Category::Symbols },
    Entry { ch: "❣️", name: "heart exclamation", shortcode: "heavy_heart_exclamation", keywords: &["love"], category: Category::Symbols },
    Entry { ch: "💕", name: "two hearts", shortcode: "two_hearts", keywords: &["love"], category: Category::Symbols },
    Entry { ch: "💞", name: "revolving hearts", shortcode: "revolving_hearts", keywords: &["love"], category: Category::Symbols },
    Entry { ch: "💓", name: "beating heart", shortcode: "heartbeat", keywords: &["love"], category: Category::Symbols },
    Entry { ch: "💗", name: "growing heart", shortcode: "heartpulse", keywords: &["love"], category: Category::Symbols },
    Entry { ch: "💖", name: "sparkling heart", shortcode: "sparkling_heart", keywords: &["love"], category: Category::Symbols },
    Entry { ch: "💘", name: "heart with arrow", shortcode: "cupid", keywords: &["love"], category: Category::Symbols },
    Entry { ch: "💝", name: "heart with ribbon", shortcode: "gift_heart", keywords: &["love"], category: Category::Symbols },
    Entry { ch: "💟", name: "heart decoration", shortcode: "heart_decoration", keywords: &["love"], category: Category::Symbols },
    Entry { ch: "☮️", name: "peace symbol", shortcode: "peace_symbol", keywords: &["pacifism"], category: Category::Symbols },
    Entry { ch: "✝️", name: "latin cross", shortcode: "latin_cross", keywords: &["christian"], category: Category::Symbols },
    Entry { ch: "☪️", name: "star and crescent", shortcode: "star_and_crescent", keywords: &["islam"], category: Category::Symbols },
    Entry { ch: "🕉️", name: "om", shortcode: "om", keywords: &["hindu"], category: Category::Symbols },
    Entry { ch: "☸️", name: "wheel of dharma", shortcode: "wheel_of_dharma", keywords: &["buddhist"], category: Category::Symbols },
    Entry { ch: "✡️", name: "star of david", shortcode: "star_of_david", keywords: &["jewish"], category: Category::Symbols },
    Entry { ch: "♈", name: "aries", shortcode: "aries", keywords: &["zodiac"], category: Category::Symbols },
    Entry { ch: "♉", name: "taurus", shortcode: "taurus", keywords: &["zodiac"], category: Category::Symbols },
    Entry { ch: "♊", name: "gemini", shortcode: "gemini", keywords: &["zodiac"], category: Category::Symbols },
    Entry { ch: "♋", name: "cancer", shortcode: "cancer", keywords: &["zodiac"], category: Category::Symbols },
    Entry { ch: "♌", name: "leo", shortcode: "leo", keywords: &["zodiac"], category: Category::Symbols },
    Entry { ch: "♍", name: "virgo", shortcode: "virgo", keywords: &["zodiac"], category: Category::Symbols },
    Entry { ch: "♎", name: "libra", shortcode: "libra", keywords: &["zodiac"], category: Category::Symbols },
    Entry { ch: "♏", name: "scorpio", shortcode: "scorpius", keywords: &["zodiac"], category: Category::Symbols },
    Entry { ch: "♐", name: "sagittarius", shortcode: "sagittarius", keywords: &["zodiac"], category: Category::Symbols },
    Entry { ch: "♑", name: "capricorn", shortcode: "capricorn", keywords: &["zodiac"], category: Category::Symbols },
    Entry { ch: "♒", name: "aquarius", shortcode: "aquarius", keywords: &["zodiac"], category: Category::Symbols },
    Entry { ch: "♓", name: "pisces", shortcode: "pisces", keywords: &["zodiac"], category: Category::Symbols },
    Entry { ch: "⭐", name: "star", shortcode: "star", keywords: &["favorite"], category: Category::Symbols },
    Entry { ch: "🌟", name: "glowing star", shortcode: "star2", keywords: &["sparkle"], category: Category::Symbols },
    Entry { ch: "✨", name: "sparkles", shortcode: "sparkles", keywords: &["shiny"], category: Category::Symbols },
    Entry { ch: "⚡", name: "high voltage", shortcode: "zap", keywords: &["lightning"], category: Category::Symbols },
    Entry { ch: "🔥", name: "fire", shortcode: "fire", keywords: &["hot", "lit"], category: Category::Symbols },
    Entry { ch: "💥", name: "collision", shortcode: "boom", keywords: &["bang", "explosion"], category: Category::Symbols },
    Entry { ch: "💧", name: "droplet", shortcode: "droplet", keywords: &["water", "drop"], category: Category::Symbols },
    Entry { ch: "💦", name: "sweat droplets", shortcode: "sweat_drops", keywords: &["water"], category: Category::Symbols },
    Entry { ch: "💯", name: "hundred points", shortcode: "100", keywords: &["perfect"], category: Category::Symbols },
    Entry { ch: "✅", name: "check mark button", shortcode: "white_check_mark", keywords: &["yes", "done"], category: Category::Symbols },
    Entry { ch: "☑️", name: "check box with check", shortcode: "ballot_box_with_check", keywords: &["done"], category: Category::Symbols },
    Entry { ch: "✔️", name: "check mark", shortcode: "heavy_check_mark", keywords: &["done"], category: Category::Symbols },
    Entry { ch: "❌", name: "cross mark", shortcode: "x", keywords: &["no", "wrong"], category: Category::Symbols },
    Entry { ch: "❎", name: "cross mark button", shortcode: "negative_squared_cross_mark", keywords: &["no"], category: Category::Symbols },
    Entry { ch: "⚠️", name: "warning", shortcode: "warning", keywords: &["caution"], category: Category::Symbols },
    Entry { ch: "❗", name: "exclamation", shortcode: "exclamation", keywords: &["alert"], category: Category::Symbols },
    Entry { ch: "❓", name: "question", shortcode: "question", keywords: &["help"], category: Category::Symbols },
    Entry { ch: "❕", name: "white exclamation", shortcode: "grey_exclamation", keywords: &["alert"], category: Category::Symbols },
    Entry { ch: "❔", name: "white question", shortcode: "grey_question", keywords: &["help"], category: Category::Symbols },
    Entry { ch: "🆗", name: "OK button", shortcode: "ok", keywords: &["okay"], category: Category::Symbols },
    Entry { ch: "🆕", name: "NEW button", shortcode: "new", keywords: &["fresh"], category: Category::Symbols },
    Entry { ch: "🆒", name: "COOL button", shortcode: "cool", keywords: &["nice"], category: Category::Symbols },
    Entry { ch: "🆓", name: "FREE button", shortcode: "free", keywords: &["gratis"], category: Category::Symbols },
    Entry { ch: "🆙", name: "UP button", shortcode: "up", keywords: &["arrow"], category: Category::Symbols },
    Entry { ch: "♻️", name: "recycling symbol", shortcode: "recycle", keywords: &["green"], category: Category::Symbols },
    Entry { ch: "➕", name: "plus", shortcode: "heavy_plus_sign", keywords: &["add"], category: Category::Symbols },
    Entry { ch: "➖", name: "minus", shortcode: "heavy_minus_sign", keywords: &["subtract"], category: Category::Symbols },
    Entry { ch: "✖️", name: "multiply", shortcode: "heavy_multiplication_x", keywords: &["times"], category: Category::Symbols },
    Entry { ch: "➗", name: "divide", shortcode: "heavy_division_sign", keywords: &["division"], category: Category::Symbols },
    Entry { ch: "🟢", name: "green circle", shortcode: "green_circle", keywords: &["online", "go"], category: Category::Symbols },
    Entry { ch: "🔴", name: "red circle", shortcode: "red_circle", keywords: &["stop"], category: Category::Symbols },
    Entry { ch: "🟡", name: "yellow circle", shortcode: "yellow_circle", keywords: &["caution"], category: Category::Symbols },
    Entry { ch: "🟠", name: "orange circle", shortcode: "orange_circle", keywords: &["warning"], category: Category::Symbols },
    Entry { ch: "🟣", name: "purple circle", shortcode: "purple_circle", keywords: &["color"], category: Category::Symbols },
    Entry { ch: "🟤", name: "brown circle", shortcode: "brown_circle", keywords: &["color"], category: Category::Symbols },
    Entry { ch: "⚫", name: "black circle", shortcode: "black_circle", keywords: &["dot"], category: Category::Symbols },
    Entry { ch: "⚪", name: "white circle", shortcode: "white_circle", keywords: &["dot"], category: Category::Symbols },
];
